[theme]
theme = "semi-native"

[icons]
icons = "awesome6"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "backlight"
device = "amdgpu_bl1"
format = " $icon $brightness "

[[block]]
block = "sound"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
